version: "3.9"

services:
  web:
    build: .
    container_name: tourism-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://tourist:123@db:5432/tourism_db
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: tourism_db
    restart: always
    environment:
      POSTGRES_USER: tourist
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tourism_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: