services:
  web:
    build: .
    container_name: tourism-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://tourist:123@db:5432/tourism_db
      - PYTHONPATH=/app
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: tourism_db
    restart: always
    environment:
      POSTGRES_USER: tourist
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tourism_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  frontend:
#    build: ./frontend
#    container_name: frontend
#    expose:
#      - "4173"
#    depends_on:
#      - web

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: tourism-nginx
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  postgres_data: