services:
  web:
    build: .
    container_name: tourism-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://tourist:123@db:5432/tourism_db
      - FLASK_APP=app:create_app
      - PYTHONPATH=/app
      - FLASK_ENV=development
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: tourism_db
    restart: always
    environment:
      POSTGRES_USER: tourist
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tourism_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - web

volumes:
  postgres_data: