"""init

Revision ID: ea0888bda84d
Revises: 
Create Date: 2026-05-07 02:41:40.905011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0888bda84d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('destinations', sa.Column('tour_type', sa.String(length=50), nullable=True))
    op.add_column('destinations', sa.Column('hotel_stars', sa.Integer(), nullable=True))
    op.add_column('destinations', sa.Column('transfer', sa.Boolean(), nullable=True))
    op.add_column('destinations', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('refresh_tokens', 'token_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('destinations', 'created_at')
    op.drop_column('destinations', 'transfer')
    op.drop_column('destinations', 'hotel_stars')
    op.drop_column('destinations', 'tour_type')
    # ### end Alembic commands ###
